# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadd87d24e419b3fb585c63d6d996041e690a4e00467e37d9e2ab1e6eb24ea5b6d1ab143973c9e7fff14bb4be876d5681328ce3d998b793dd932fa6c345fe46a

test:
  secret_key_base: 0b84445f6e6fe192fd4962623d96824da2c62ff3447275b0a5ddf7ad9bb53ac0cbfd4f10aad48711d3ddc96d512c3b09cdce1775bcb6432184c5bee7a01d1a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
